<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

use Illuminate\Support\Carbon;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = Hash::make(123456789);
        $array = array(100, 200, 300);
        $user = [
            [
                'lastName' => "Admin",
                'firstName' => "Admin",
                'sex' => "Women",
                'email' => "admin@gmail.com",
                'emailProf' => "admin@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11717895",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11177895",
                'matricule' => "87a74-148l4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'As5Z01669218048.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Zaineb",
                'firstName' => "Zaineb",
                'sex' => "Women",
                'email' => "zaineb@gmail.com",
                'emailProf' => "zaineb@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11777895",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11777895",
                'matricule' => "87a74-148l4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'HOAuX1669218064.jpeg',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Selim",
                'firstName' => "Selim",
                'sex' => "Man",
                'email' => "selim@gmail.com",
                'emailProf' => "selim@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 55 825 825",
                'phoneEmergency' => "+216 55 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "12545666",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"12545666",
                'matricule' => "696rrr-az78",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'Q58Kx1669218097.webp',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Houcem",
                'firstName' => "Hedhly",
                'sex' => "Man",
                'email' => "houcemH@gmail.com",
                'emailProf' => "houcemH@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11162526",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11277526",
                'matricule' => "87a14-14aa4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'lastName' => "Mohamed",
                'firstName' => "Mohamed",
                'sex' => "Man",
                'email' => "mohamed@gmail.com",
                'emailProf' => "mohamed@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 25 825 825",
                'phoneEmergency' => "+216 25 825 855",
                'FamilySituation' => "Single",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11111111",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11223344",
                'integrationDate'=> '2022-10-31',
                'matricule' => "12a58-8z4",
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Mourad",
                'firstName' => "Mourad",
                'sex' => "Man",
                'email' => "mourad@gmail.com",
                'emailProf' => "mourad@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11772526",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11772526",
                'matricule' => "87a94-14aa4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],


            [
                'lastName' => "Mariem",
                'firstName' => "Mariem",
                'sex' => "Women",
                'email' => "mariem@gmail.com",
                'emailProf' => "mariem@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11225665",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11225665",
                'matricule' => "87a14-147",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ], [
                'lastName' => "Nour",
                'firstName' => "Nour",
                'sex' => "Women",
                'email' => "nour@gmail.com",
                'emailProf' => "nour@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "15458566",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"85528599",
                'matricule' => "87a14-14777",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Hamdi",
                'firstName' => "Hamdi",
                'sex' => "Man",
                'email' => "hamdi@gmail.com",
                'emailProf' => "hamdi@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11262526",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"13262526",
                'matricule' => "87a14-14a7",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Houcem",
                'firstName' => "bozrati",
                'sex' => "Man",
                'email' => "houcemB@gmail.com",
                'emailProf' => "houcemB@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "19262526",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11287526",
                'matricule' => "87a14-14aa4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Ishak",
                'firstName' => "Ishak",
                'sex' => "Man",
                'email' => "ishak@gmail.com",
                'emailProf' => "ishak@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11772555",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11772555",
                'matricule' => "87a94-148a4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Dali(cc)",
                'firstName' => "Dali(cc)",
                'sex' => "Man",
                'email' => "dali@gmail.com",
                'emailProf' => "dali@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11777755",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11777755",
                'matricule' => "87a94-148l4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Houcem(cc)",
                'firstName' => "Houcem(cc)",
                'sex' => "Man",
                'email' => "houcem@gmail.com",
                'emailProf' => "houcem@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11377895",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11377895",
                'matricule' => "87a7-148l4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Amal",
                'firstName' => "Amal",
                'sex' => "Women",
                'email' => "amal@gmail.com",
                'emailProf' => "amal@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 25 825 825",
                'phoneEmergency' => "+216 25 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "22222222",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"44332211",
                'matricule' => "87a14-az78",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Marwa",
                'firstName' => "Marwa",
                'sex' => "Women",
                'email' => "marwa@gmail.com",
                'emailProf' => "marwa@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 52 825 825",
                'phoneEmergency' => "+216 52 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "66666666",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"96385485",
                'matricule' => "666i1-az78",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Karim",
                'firstName' => "Karim",
                'sex' => "Man",
                'email' => "karim@gmail.com",
                'emailProf' => "karim@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 55 825 825",
                'phoneEmergency' => "+216 55 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "99999999",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"44444444",
                'matricule' => "696rrr-az78",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Oumaima",
                'firstName' => "Oumaima",
                'sex' => "Women",
                'email' => "oumaima@gmail.com",
                'emailProf' => "oumaima@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisienne",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "77777777",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"85528522",
                'matricule' => "87a14-14777",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'lastName' => "Maz",
                'firstName' => "Maz",
                'sex' => "Man",
                'email' => "maz@gmail.com",
                'emailProf' => "maz@digitrends.dev",
                'address' => "Bizerte",
                'placeBirth' => "Tunis",
                'dateBirth' => '2004-01-01',
                'nationality' => "Tunisien",
                'phone' => "+216 28 825 825",
                'phoneEmergency' => "+216 28 825 855",
                'FamilySituation' => "Married",
                'status' => "active",
                'nbChildren' => "0",
                'pwd_reset_admin' => 0,
                'levelStudies' => "Bac + 3",
                'specialty' => "informatique",
                'sivp' => "No",
                'durationSivp' =>  "0",
                'cin' =>  "11377899",
                'deliveryDateCin' => '2022-01-01',
                'deliveryPlaceCin' =>"Bizerte",
                'numPassport' =>"11397899",
                'matricule' => "898a7-148l4",
                'integrationDate'=> '2022-10-31',
                'password' => $password,
                'image'=>'img.png',
                'is_deleted'=>0,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        User::insert($user);
    }
}
